Repository laminas/laminas-developer-tools, pull requests merged in 2020-11, with the labels that each got.

#34 Improve PHPDoc return- and paramter-types
  src/Collector/DbCollector.php
  src/Collector/RequestCollector.php
  src/EventLogging/EventContextInterface.php
  src/EventLogging/EventContextProvider.php
  src/Listener/EventLoggingListenerAggregate.php
  src/Module.php
  src/Profiler.php
  src/Report.php
Labels: Bug

#31 Fixes #1 : Toolbar should be displayed even without <head> in HTML5
  CHANGELOG.md
  src/Listener/ToolbarListener.php
  test/Listener/ToolbarListenerTest.php
Labels: Enhancement

#33 Add PHP 8.0 support
  .travis.yml
  composer.json
  phpunit.xml.dist
  test/Collector/MemoryCollectorTest.php
  test/ModuleTest.php
  test/OptionsTest.php
Labels: Enhancement, hacktoberfest-accepted
